# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'github_topic_app' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for github_topic_app
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Alamofire'
  pod 'AlamofireImage'

  target 'github_topic_appTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'github_topic_appUITests' do
    # Pods for testing
  end

end
